package io.github.unurgunite.crystal.lexer

import com.intellij.psi.tree.IElementType
import com.intellij.psi.tree.TokenSet
import io.github.unurgunite.crystal.CrystalLanguage
import io.github.unurgunite.crystal.psi.CrystalTypes

class CrystalTokenType(debugName: String) : IElementType(debugName, CrystalLanguage) {
    override fun toString(): String = "CrystalTokenType.${super.toString()}"
}

object CrystalTokenTypes {
    // Non-BNF tokens (not generated by GrammarKit)
    @JvmField val WHITE_SPACE = com.intellij.psi.TokenType.WHITE_SPACE
    @JvmField val BAD_CHARACTER = com.intellij.psi.TokenType.BAD_CHARACTER

    // Token sets (referencing CrystalTypes — the single source of truth)
    @JvmField val KEYWORDS = TokenSet.create(
        CrystalTypes.ABSTRACT, CrystalTypes.ALIAS, CrystalTypes.ANNOTATION,
        CrystalTypes.AS, CrystalTypes.AS_QUESTION, CrystalTypes.ASM,
        CrystalTypes.BEGIN, CrystalTypes.BREAK, CrystalTypes.CASE,
        CrystalTypes.CLASS, CrystalTypes.DEF, CrystalTypes.DO,
        CrystalTypes.ELSE, CrystalTypes.ELSIF, CrystalTypes.END,
        CrystalTypes.ENSURE, CrystalTypes.ENUM, CrystalTypes.EXTEND,
        CrystalTypes.FALSE, CrystalTypes.FOR, CrystalTypes.FORALL, CrystalTypes.FUN,
        CrystalTypes.IF, CrystalTypes.IN, CrystalTypes.INCLUDE,
        CrystalTypes.INSTANCE_SIZEOF, CrystalTypes.IS_A,
        CrystalTypes.LIB, CrystalTypes.MACRO, CrystalTypes.MODULE,
        CrystalTypes.NEXT, CrystalTypes.NIL, CrystalTypes.NIL_QUESTION,
        CrystalTypes.OF, CrystalTypes.OFFSETOF, CrystalTypes.OUT,
        CrystalTypes.POINTEROF, CrystalTypes.PREVIOUS_DEF,
        CrystalTypes.PRIVATE, CrystalTypes.PROTECTED,
        CrystalTypes.REQUIRE, CrystalTypes.RESCUE, CrystalTypes.RESPONDS_TO,
        CrystalTypes.RETURN, CrystalTypes.SELECT, CrystalTypes.SELF,
        CrystalTypes.SIZEOF, CrystalTypes.STRUCT, CrystalTypes.SUPER,
        CrystalTypes.THEN, CrystalTypes.TRUE, CrystalTypes.TYPEOF,
        CrystalTypes.UNINITIALIZED, CrystalTypes.UNION, CrystalTypes.UNLESS,
        CrystalTypes.UNTIL, CrystalTypes.VERBATIM, CrystalTypes.WHEN,
        CrystalTypes.WHILE, CrystalTypes.WITH, CrystalTypes.YIELD
    )

    @JvmField val COMMENTS = TokenSet.create(CrystalTypes.LINE_COMMENT)

    @JvmField val STRINGS = TokenSet.create(
        CrystalTypes.STRING_LITERAL, CrystalTypes.CHAR_LITERAL,
        CrystalTypes.COMMAND_LITERAL,
        CrystalTypes.HEREDOC_CONTENT, CrystalTypes.HEREDOC_START,
        CrystalTypes.HEREDOC_END,
        CrystalTypes.PERCENT_LITERAL_BEGIN, CrystalTypes.PERCENT_LITERAL_END
    )

    @JvmField val NUMBERS = TokenSet.create(
        CrystalTypes.INTEGER_LITERAL, CrystalTypes.FLOAT_LITERAL
    )

    @JvmField val OPERATORS = TokenSet.create(
        CrystalTypes.PLUS, CrystalTypes.MINUS, CrystalTypes.STAR,
        CrystalTypes.SLASH, CrystalTypes.DOUBLE_SLASH, CrystalTypes.PERCENT,
        CrystalTypes.AMPERSAND, CrystalTypes.PIPE, CrystalTypes.CARET,
        CrystalTypes.TILDE, CrystalTypes.DOUBLE_STAR,
        CrystalTypes.WRAP_PLUS, CrystalTypes.WRAP_MINUS,
        CrystalTypes.WRAP_STAR, CrystalTypes.WRAP_DOUBLE_STAR,
        CrystalTypes.LSHIFT, CrystalTypes.RSHIFT,
        CrystalTypes.EQ, CrystalTypes.NEQ, CrystalTypes.LT, CrystalTypes.GT,
        CrystalTypes.LTE, CrystalTypes.GTE, CrystalTypes.SPACESHIP,
        CrystalTypes.CASE_EQ, CrystalTypes.MATCH_OP, CrystalTypes.BANG,
        CrystalTypes.AND_AND, CrystalTypes.OR_OR, CrystalTypes.ASSIGN,
        CrystalTypes.PLUS_ASSIGN, CrystalTypes.MINUS_ASSIGN,
        CrystalTypes.STAR_ASSIGN, CrystalTypes.SLASH_ASSIGN,
        CrystalTypes.PERCENT_ASSIGN, CrystalTypes.AMPERSAND_ASSIGN,
        CrystalTypes.PIPE_ASSIGN, CrystalTypes.CARET_ASSIGN,
        CrystalTypes.DOUBLE_STAR_ASSIGN, CrystalTypes.DOUBLE_SLASH_ASSIGN,
        CrystalTypes.WRAP_PLUS_ASSIGN, CrystalTypes.WRAP_MINUS_ASSIGN,
        CrystalTypes.WRAP_STAR_ASSIGN, CrystalTypes.WRAP_DOUBLE_STAR_ASSIGN,
        CrystalTypes.LSHIFT_ASSIGN,
        CrystalTypes.RSHIFT_ASSIGN, CrystalTypes.OR_OR_ASSIGN,
        CrystalTypes.AND_AND_ASSIGN,
        CrystalTypes.DOT, CrystalTypes.DOTDOT, CrystalTypes.DOTDOTDOT,
        CrystalTypes.ARROW, CrystalTypes.DOUBLE_ARROW,
        CrystalTypes.QUESTION, CrystalTypes.COLON, CrystalTypes.DOUBLE_COLON
    )
}
